# Generated by Django 5.1.6 on 2025-10-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikitos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Фото'),
        ),
    ]
